version: "2"

services:
  python:
    build: .
    image: YOUR-USER-NAME/cbc
    restart: always
    ports:
      - "127.0.0.1:8302:1337"
    environment:
      - GZCTF_FLAG=flag{kfccrazythursdayvme50}